openapi: 3.0.3
info:
  title: Serverless WebSocket AWS - OpenAPI 3.0
  description: Service integration Serverless WebSocket AWS
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://host.swagger.io/api/v3
tags:
  - name: swa
    description: Everything about SWA
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /swa:
    get:
      tags:
        - swa
      summary: Finds websocket
      description: Finds websocket
      operationId: findSWA
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/xml:
              schema:
                type: array
                items: {}
        '400':
          description: Invalid status value
